name: rna-seq-pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - nextflow
  - fastqc
  - multiqc
  - hisat2
  - samtools
  - subread
  - r-base
  - bioconductor-deseq2
  - r-ggplot2
  - python
  - watchdog
  - pandas
